#pragma once

#define DYNAMIC_KEYMAP_LAYER_COUNT 5

// Tri-layer definitions
#define TRI_LAYER_LOWER_LAYER 2
#define TRI_LAYER_UPPER_LAYER 3
#define TRI_LAYER_ADJUST_LAYER 4

// RGB Lighting
#undef RGB_BACKLIGHT_DISABLE_WHEN_USB_SUSPENDED
#undef RGB_BACKLIGHT_DISABLE_AFTER_TIMEOUT
#define RGB_BACKLIGHT_DISABLE_WHEN_USB_SUSPENDED 1
#define RGB_BACKLIGHT_DISABLE_AFTER_TIMEOUT 30

// Define colors for RGB backlight
#undef RGB_BACKLIGHT_EFFECT
#undef RGB_BACKLIGHT_COLOR_1
#undef RGB_BACKLIGHT_COLOR_2
#define RGB_BACKLIGHT_EFFECT 1
#define RGB_BACKLIGHT_COLOR_1 { .h = 0, .s = 0 }
#define RGB_BACKLIGHT_COLOR_2 { .h = 0, .s = 0 }
